meta_product_name: "Runation"
meta_title: "Runation - Product tagline"
meta_description: "Runation is the ultimate platform for passionate runners and outdoor enthusiasts. Track your progress, connect with a vibrant community, and challenge yourself to new heights. Empower your running journey with innovative tools and a dash of adventure!"
meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account" # required for Twitter Cards
